// Generated by gencpp from file ddynamic_reconfigure/TutorialParamsRequest.msg
// DO NOT EDIT!


#ifndef DDYNAMIC_RECONFIGURE_MESSAGE_TUTORIALPARAMSREQUEST_H
#define DDYNAMIC_RECONFIGURE_MESSAGE_TUTORIALPARAMSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ddynamic_reconfigure
{
template <class ContainerAllocator>
struct TutorialParamsRequest_
{
  typedef TutorialParamsRequest_<ContainerAllocator> Type;

  TutorialParamsRequest_()
    {
    }
  TutorialParamsRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::ddynamic_reconfigure::TutorialParamsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ddynamic_reconfigure::TutorialParamsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TutorialParamsRequest_

typedef ::ddynamic_reconfigure::TutorialParamsRequest_<std::allocator<void> > TutorialParamsRequest;

typedef boost::shared_ptr< ::ddynamic_reconfigure::TutorialParamsRequest > TutorialParamsRequestPtr;
typedef boost::shared_ptr< ::ddynamic_reconfigure::TutorialParamsRequest const> TutorialParamsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ddynamic_reconfigure::TutorialParamsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ddynamic_reconfigure::TutorialParamsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace ddynamic_reconfigure

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ddynamic_reconfigure::TutorialParamsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ddynamic_reconfigure::TutorialParamsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ddynamic_reconfigure::TutorialParamsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ddynamic_reconfigure::TutorialParamsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ddynamic_reconfigure::TutorialParamsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ddynamic_reconfigure::TutorialParamsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ddynamic_reconfigure::TutorialParamsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::ddynamic_reconfigure::TutorialParamsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::ddynamic_reconfigure::TutorialParamsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ddynamic_reconfigure/TutorialParamsRequest";
  }

  static const char* value(const ::ddynamic_reconfigure::TutorialParamsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ddynamic_reconfigure::TutorialParamsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::ddynamic_reconfigure::TutorialParamsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ddynamic_reconfigure::TutorialParamsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TutorialParamsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ddynamic_reconfigure::TutorialParamsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::ddynamic_reconfigure::TutorialParamsRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // DDYNAMIC_RECONFIGURE_MESSAGE_TUTORIALPARAMSREQUEST_H
